# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kdeclarative': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kio': '@stable'
    'pim/akonadi': '@same'
    'pim/akonadi-contacts': '@same'
    'pim/akonadi-mime': '@same'
    'pim/mailcommon': '@same'
    'pim/pimcommon': '@same'
    'pim/libkdepim': '@same'
    'pim/kldap': '@same'
    'pim/kmime': '@same'
    'pim/kmailtransport': '@same'
    'pim/messagelib': '@same'
    'libraries/kirigami-addons': '@latest'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
