# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kdeclarative': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kio': '@stable'
    'libraries/kirigami-addons': '@latest'
